# Generated by Django 6.0.5 on 2026-05-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'CARD'), ('BANK', 'BANK')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_fraud', models.BooleanField(default=False)),
                ('fraud_score', models.FloatField(default=0.0)),
            ],
        ),
    ]
