# Generated by Django 6.0.5 on 2026-05-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fraud_score',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ip_address',
        ),
    ]
